class XtdGearModels {
    #include "XtdGearModels_Common.hpp"
    class CfgWeapons {
        #include "XtdGearModels\config\CfgWeapons\STEVE_Volkite_Charger_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_UmbraBoltgun_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_TigrusExitusBoltgun_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_TigrusBoltgun_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_Tigrus_Combi_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_SM_LasCan_01.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Ryza_Plasma_01.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Rotor_Cannon_01.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Primus_Metla_01.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_PhobosCombiBolt_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_PhobosBoltgun_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_Phobos_Atrox_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Phaistos_Heavy_Flamer_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Phaestos_Flamer_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Auto_Cannon_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_Volkite_Cav_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Shotgun_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_LascutShield_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_30k_Plasma_cannon_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_30k_Multi_Melta_1.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Phobos_Pistol.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_Ryza_Pistol.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_30k_Tig_Pistol.hpp"
        #include "XtdGearModels\config\CfgWeapons\STEVE_30k_Volkite_Pistol.hpp"
        #include "XtdGearModels\config\CfgWeapons\Steve_30K_Rocket_1.hpp"
        
    };
};
